<?php
/**
 * reference: https://thinkshout.com/blog/2014/05/custom-date-formats-in-drupal/
 * Implements hook_date_formats().
 */
function creighton_dates_date_formats() {
    return array(
        // Creates a new format for a new, custom format type.
        array(
            'type' => 'date_day_short_start',
            'format' => 'd',
            'locales' => array(),
        ),
        // Defines a format and makes it available to core's short format type.
        array(
            'type' => 'date_month_short_start',
            'format' => 'M',
            'locales' => array(),
        ),
    );
}

/**
 * Implements hook_date_format_types().
 */
function creighton_dates_date_format_types() {
    return array(
        'date_day_short_start' => t('Short Day: d'),
        'date_month_short_start' => t('Short Month: M'),
    );
}