<?php
/**
 * @file
 * creighton_secure_login.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function creighton_secure_login_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_all_forms';
  $strongarm->value = 0;
  $export['securelogin_all_forms'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_node_form';
  $strongarm->value = 1;
  $export['securelogin_form_node_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_login';
  $strongarm->value = 1;
  $export['securelogin_form_user_login'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_login_block';
  $strongarm->value = 1;
  $export['securelogin_form_user_login_block'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_pass';
  $strongarm->value = 1;
  $export['securelogin_form_user_pass'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_pass_reset';
  $strongarm->value = 1;
  $export['securelogin_form_user_pass_reset'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_profile_form';
  $strongarm->value = 1;
  $export['securelogin_form_user_profile_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_user_register_form';
  $strongarm->value = 1;
  $export['securelogin_form_user_register_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_form_webform_client_form';
  $strongarm->value = 0;
  $export['securelogin_form_webform_client_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'securelogin_secure_forms';
  $strongarm->value = 1;
  $export['securelogin_secure_forms'] = $strongarm;

  return $export;
}
