<?php

/**
 * Implements hook_block_info().
 */
function cu_academics_search_block_info() {
  $blocks = array();
  $blocks['academics_custom_block'] = array(
    'info' => t('Academics Search'),
  );
 
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cu_academics_search_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'academics_custom_block' :
      $block['content'] = academic_program_search_block_view();
      break;
  }

  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function academic_program_search_block_view() {
  //global $base_url;
  $block = array();
  $search_form = '<div class="outline-search"><form action="/program-search" method="get"><input class="form-text" id="edit-title" maxlength="128" name="term" size="30" type="text" value="" /><input class="form-submit" id="edit-submit-program-table" name="" type="submit" value="Search" /></form></div>';


  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $search_form,      
      '#suffix' => '<nav class="simple-menu"><ul class="menu"><li><a href="http://www.creighton.edu/programs" title="View an A-Z Listing">A-Z Listing</a></li><li><a href="http://www.creighton.edu/programs?alpha=&online=2&accelerated=All&professional=All&prg_offered=All&title=" title="View available online cources">Online Courses</a></li><li><a href="http://www.creighton.edu/programs?alpha=&online=All&accelerated=All&professional=All&prg_offered=3&title=" title="View Graduate programs">Graduate Programs</a></li></ul></nav>',
      
    )
  );

  return $block;
}
