<?php
/**
 * @file
 * front_page_mini_panels_and_menus.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function front_page_mini_panels_and_menus_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-9-schools-and-colleges-col-_school-of-dentistry:https://dentistry.creighton.edu.
  $menu_links['menu-9-schools-and-colleges-col-_school-of-dentistry:https://dentistry.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges-col-',
    'link_path' => 'https://dentistry.creighton.edu',
    'router_path' => '',
    'link_title' => 'School of Dentistry',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges-col-_school-of-dentistry:https://dentistry.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges-col-_school-of-law:http://law.creighton.edu.
  $menu_links['menu-9-schools-and-colleges-col-_school-of-law:http://law.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges-col-',
    'link_path' => 'http://law.creighton.edu',
    'router_path' => '',
    'link_title' => 'School of Law',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges-col-_school-of-law:http://law.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges-col-_school-of-medicine:https://medschool.creighton.edu/.
  $menu_links['menu-9-schools-and-colleges-col-_school-of-medicine:https://medschool.creighton.edu/'] = array(
    'menu_name' => 'menu-9-schools-and-colleges-col-',
    'link_path' => 'https://medschool.creighton.edu/',
    'router_path' => '',
    'link_title' => 'School of Medicine',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges-col-_school-of-medicine:https://medschool.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges-col-_school-of-pharmacy-and-health-professions:https://spahp.creighton.edu/.
  $menu_links['menu-9-schools-and-colleges-col-_school-of-pharmacy-and-health-professions:https://spahp.creighton.edu/'] = array(
    'menu_name' => 'menu-9-schools-and-colleges-col-',
    'link_path' => 'https://spahp.creighton.edu/',
    'router_path' => '',
    'link_title' => 'School of Pharmacy and Health Professions',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges-col-_school-of-pharmacy-and-health-professions:https://spahp.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges_college-of-arts-and-sciences:https://ccas.creighton.edu.
  $menu_links['menu-9-schools-and-colleges_college-of-arts-and-sciences:https://ccas.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges',
    'link_path' => 'https://ccas.creighton.edu',
    'router_path' => '',
    'link_title' => 'College of Arts and Sciences',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges_college-of-arts-and-sciences:https://ccas.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges_college-of-nursing:https://nursing.creighton.edu.
  $menu_links['menu-9-schools-and-colleges_college-of-nursing:https://nursing.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges',
    'link_path' => 'https://nursing.creighton.edu',
    'router_path' => '',
    'link_title' => 'College of Nursing',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges_college-of-nursing:https://nursing.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges_college-of-professional-studies:https://adultdegrees.creighton.edu.
  $menu_links['menu-9-schools-and-colleges_college-of-professional-studies:https://adultdegrees.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges',
    'link_path' => 'https://adultdegrees.creighton.edu',
    'router_path' => '',
    'link_title' => 'College of Professional Studies',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges_college-of-professional-studies:https://adultdegrees.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges_graduate-school:https://gradschool.creighton.edu.
  $menu_links['menu-9-schools-and-colleges_graduate-school:https://gradschool.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges',
    'link_path' => 'https://gradschool.creighton.edu',
    'router_path' => '',
    'link_title' => 'Graduate School',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges_graduate-school:https://gradschool.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-9-schools-and-colleges_heider-college-of-business:https://business.creighton.edu.
  $menu_links['menu-9-schools-and-colleges_heider-college-of-business:https://business.creighton.edu'] = array(
    'menu_name' => 'menu-9-schools-and-colleges',
    'link_path' => 'https://business.creighton.edu',
    'router_path' => '',
    'link_title' => 'Heider College of Business',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-9-schools-and-colleges_heider-college-of-business:https://business.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for-col-2_alumni-and-friends:https://alumni.creighton.edu/.
  $menu_links['menu-information-for-col-2_alumni-and-friends:https://alumni.creighton.edu/'] = array(
    'menu_name' => 'menu-information-for-col-2',
    'link_path' => 'https://alumni.creighton.edu/',
    'router_path' => '',
    'link_title' => 'Alumni and Friends',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for-col-2_alumni-and-friends:https://alumni.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for-col-2_donors:https://alumni.creighton.edu/give-back.
  $menu_links['menu-information-for-col-2_donors:https://alumni.creighton.edu/give-back'] = array(
    'menu_name' => 'menu-information-for-col-2',
    'link_path' => 'https://alumni.creighton.edu/give-back',
    'router_path' => '',
    'link_title' => 'Donors',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for-col-2_donors:https://alumni.creighton.edu/give-back',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for-col-2_faculty-and-staff:https://www.creighton.edu/faculty-staff.
  $menu_links['menu-information-for-col-2_faculty-and-staff:https://www.creighton.edu/faculty-staff'] = array(
    'menu_name' => 'menu-information-for-col-2',
    'link_path' => 'https://www.creighton.edu/faculty-staff',
    'router_path' => '',
    'link_title' => 'Faculty and Staff',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/all/themes/custom/web_themes/creighton_2016/images/megamenu-icons/mega-menu-sprites.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for-col-2_faculty-and-staff:https://www.creighton.edu/faculty-staff',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for-col-2_parents-and-visitors:https://www.creighton.edu/parents.
  $menu_links['menu-information-for-col-2_parents-and-visitors:https://www.creighton.edu/parents'] = array(
    'menu_name' => 'menu-information-for-col-2',
    'link_path' => 'https://www.creighton.edu/parents',
    'router_path' => '',
    'link_title' => 'Parents and Visitors',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for-col-2_parents-and-visitors:https://www.creighton.edu/parents',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for_adult-students:https://adultdegrees.creighton.edu.
  $menu_links['menu-information-for_adult-students:https://adultdegrees.creighton.edu'] = array(
    'menu_name' => 'menu-information-for',
    'link_path' => 'https://adultdegrees.creighton.edu',
    'router_path' => '',
    'link_title' => 'Adult Students',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for_adult-students:https://adultdegrees.creighton.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for_current-students:https://www.creighton.edu/current-students.
  $menu_links['menu-information-for_current-students:https://www.creighton.edu/current-students'] = array(
    'menu_name' => 'menu-information-for',
    'link_path' => 'https://www.creighton.edu/current-students',
    'router_path' => '',
    'link_title' => 'Current Students',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for_current-students:https://www.creighton.edu/current-students',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for_future-students:https://www.creighton.edu/admissions.
  $menu_links['menu-information-for_future-students:https://www.creighton.edu/admissions'] = array(
    'menu_name' => 'menu-information-for',
    'link_path' => 'https://www.creighton.edu/admissions',
    'router_path' => '',
    'link_title' => 'Future Students',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for_future-students:https://www.creighton.edu/admissions',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for_militaryveteran-students:http://www.creighton.edu/mil/.
  $menu_links['menu-information-for_militaryveteran-students:http://www.creighton.edu/mil/'] = array(
    'menu_name' => 'menu-information-for',
    'link_path' => 'http://www.creighton.edu/mil/',
    'router_path' => '',
    'link_title' => 'Military/Veteran Students',
    'options' => array(
      'attributes' => array(
        'title' => '',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for_militaryveteran-students:http://www.creighton.edu/mil/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-information-for_online-students:https://www.creighton.edu/online-students.
  $menu_links['menu-information-for_online-students:https://www.creighton.edu/online-students'] = array(
    'menu_name' => 'menu-information-for',
    'link_path' => 'https://www.creighton.edu/online-students',
    'router_path' => '',
    'link_title' => 'Online Students',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/all/themes/custom/web_themes/creighton_2016/images/megamenu-icons/mega-menu-sprites.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-information-for_online-students:https://www.creighton.edu/online-students',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-menu-icons_campus-maps:http://www.creighton.edu/maps/.
  $menu_links['menu-menu-icons_campus-maps:http://www.creighton.edu/maps/'] = array(
    'menu_name' => 'menu-menu-icons',
    'link_path' => 'http://www.creighton.edu/maps/',
    'router_path' => '',
    'link_title' => 'Campus Maps',
    'options' => array(
      'attributes' => array(
        'title' => 'Campus Maps',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-menu-icons_campus-maps:http://www.creighton.edu/maps/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-menu-icons_make-a-gift:https://securelb.imodules.com/s/1250/15/site/index.aspx?sid=1250&gid=1&pgid=1880&cid=4250.
  $menu_links['menu-menu-icons_make-a-gift:https://securelb.imodules.com/s/1250/15/site/index.aspx?sid=1250&gid=1&pgid=1880&cid=4250'] = array(
    'menu_name' => 'menu-menu-icons',
    'link_path' => 'https://securelb.imodules.com/s/1250/15/site/index.aspx?sid=1250&gid=1&pgid=1880&cid=4250',
    'router_path' => '',
    'link_title' => 'Make a Gift',
    'options' => array(
      'attributes' => array(
        'title' => 'Make a Gift',
        'class' => array(
          0 => 'menu_icon',
          1 => 'menu-29793',
        ),
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 1,
        'path' => 'public://sites/all/themes/custom/web_themes/creighton_2016/images/megamenu-icons/mega-menu-azindex.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-menu-icons_make-a-gift:https://securelb.imodules.com/s/1250/15/site/index.aspx?sid=1250&gid=1&pgid=1880&cid=4250',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_blueline:https://blueline.instructure.com/.
  $menu_links['menu-resources_blueline:https://blueline.instructure.com/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'https://blueline.instructure.com/',
    'router_path' => '',
    'link_title' => 'BlueLine',
    'options' => array(
      'attributes' => array(
        'title' => 'BlueLine',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_blueline:https://blueline.instructure.com/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_bookstore:http://www.bkstr.com/creightonstore/home.
  $menu_links['menu-resources_bookstore:http://www.bkstr.com/creightonstore/home'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'http://www.bkstr.com/creightonstore/home',
    'router_path' => '',
    'link_title' => 'Bookstore',
    'options' => array(
      'attributes' => array(
        'title' => 'Bookstore',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_bookstore:http://www.bkstr.com/creightonstore/home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_calendar:http://calendar.creighton.edu/.
  $menu_links['menu-resources_calendar:http://calendar.creighton.edu/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'http://calendar.creighton.edu/',
    'router_path' => '',
    'link_title' => 'Calendar',
    'options' => array(
      'attributes' => array(
        'title' => 'Calendar',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_calendar:http://calendar.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 6,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_directory:https://ami.creighton.edu/.
  $menu_links['menu-resources_directory:https://ami.creighton.edu/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'https://ami.creighton.edu/',
    'router_path' => '',
    'link_title' => 'Directory',
    'options' => array(
      'attributes' => array(
        'title' => 'Directory',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_directory:https://ami.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_libraries:http://www.creighton.edu/libraries/.
  $menu_links['menu-resources_libraries:http://www.creighton.edu/libraries/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'http://www.creighton.edu/libraries/',
    'router_path' => '',
    'link_title' => 'Libraries',
    'options' => array(
      'attributes' => array(
        'title' => 'Libraries',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_libraries:http://www.creighton.edu/libraries/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_media:http://www.creighton.edu/publicrelations/newscenter/.
  $menu_links['menu-resources_media:http://www.creighton.edu/publicrelations/newscenter/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'http://www.creighton.edu/publicrelations/newscenter/',
    'router_path' => '',
    'link_title' => 'Media',
    'options' => array(
      'attributes' => array(
        'title' => 'Media',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_media:http://www.creighton.edu/publicrelations/newscenter/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 8,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_nest:https://thenest.creighton.edu/PROD/twbkwbis.P_GenMenu?name=homepage.
  $menu_links['menu-resources_nest:https://thenest.creighton.edu/PROD/twbkwbis.P_GenMenu?name=homepage'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'https://thenest.creighton.edu/PROD/twbkwbis.P_GenMenu?name=homepage',
    'router_path' => '',
    'link_title' => 'NEST',
    'options' => array(
      'attributes' => array(
        'title' => 'NEST',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_nest:https://thenest.creighton.edu/PROD/twbkwbis.P_GenMenu?name=homepage',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 3,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_office365:http://office365.creighton.edu/.
  $menu_links['menu-resources_office365:http://office365.creighton.edu/'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'http://office365.creighton.edu/',
    'router_path' => '',
    'link_title' => 'Office365',
    'options' => array(
      'attributes' => array(
        'title' => 'Office365',
        'target' => array(
          0 => '_blank',
        ),
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_office365:http://office365.creighton.edu/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 1,
  );
  // Exported menu link: menu-resources_public-safety:https://www.creighton.edu/safety.
  $menu_links['menu-resources_public-safety:https://www.creighton.edu/safety'] = array(
    'menu_name' => 'menu-resources',
    'link_path' => 'https://www.creighton.edu/safety',
    'router_path' => '',
    'link_title' => 'Public Safety',
    'options' => array(
      'attributes' => array(
        'title' => 'Public Safety',
      ),
      'menu_icon' => array(
        'enable' => 0,
        'path' => 'sites/www-retheme.web-dev.creighton.edu/modules/menu_icons/images/default_icon.png',
        'image_style' => 'menu_icon',
      ),
      'identifier' => 'menu-resources_public-safety:https://www.creighton.edu/safety',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 7,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Adult Students');
  t('Alumni and Friends');
  t('BlueLine');
  t('Bookstore');
  t('Calendar');
  t('Campus Maps');
  t('College of Arts and Sciences');
  t('College of Nursing');
  t('College of Professional Studies');
  t('Current Students');
  t('Directory');
  t('Donors');
  t('Faculty and Staff');
  t('Future Students');
  t('Graduate School');
  t('Heider College of Business');
  t('Libraries');
  t('Make a Gift');
  t('Media');
  t('Military/Veteran Students');
  t('NEST');
  t('Office365');
  t('Online Students');
  t('Parents and Visitors');
  t('Public Safety');
  t('School of Dentistry');
  t('School of Law');
  t('School of Medicine');
  t('School of Pharmacy and Health Professions');

  return $menu_links;
}
