name = Front Page Layout
description = Creighton University's front page (homepage) layout.
preview = preview.png
template = cu-front-layout

; NOTE: Please make layouts/cu-default/cu-default.layout.inc regions match these regions else problems will ensue
regions[alert_header] = Alert Header
regions[header] = Main Header
regions[secondary_header] = Secondary Header
regions[header_image] = Header Image
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[badge_footer] = Footer Badge
regions[left_footer] = Left Sidebar Footer
regions[right_footer] = Right Sidebar Footer

; Stylesheets
stylesheets[all][] = css/layouts/cu-front/cu-front.layout.css

