name = Creighton University Default
description = Creighton University's default site layout for 2013.
preview = preview.png
template = cu-default-layout

; NOTE: Please make layouts/cu-default/cu-default.layout.inc regions match these regions else problems will ensue
regions[alert_header] = Alert Header
regions[header] = Main Header
regions[secondary_header] = Secondary Header
regions[header_image] = Header Image
regions[highlighted] = Highlighted
regions[help] = Help
regions[academics_program_title] = Academics Program Title
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[badge_footer] = Footer Badge
regions[left_footer] = Left Sidebar Footer
regions[right_footer] = Right Sidebar Footer

; Stylesheets
stylesheets[all][] = css/layouts/cu-default/cu-default.layout.css

