name = 2016 Front Page Layout
description = Creighton 2016 University's front page (homepage) layout.
preview = preview.png
template = cu-front-2016-layout

; NOTE: Please make layouts/cu-default/cu-default.layout.inc regions match these regions else problems will ensue
regions[alert_header] = Alert Header
regions[header] = Main Header
regions[secondary_header] = Secondary Header
regions[header_image] = Header Image
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; Regions for Main Navigation

regions[main_nav] = Main Mega Navigation
regions[dropdown_menu] = Drop down toggle for menu

regions[header_searchbox] = Header Search
regions[header_tranlinks] = Transaction Links
regions[megamenu_dropdown] = Menu Dropdown
regions[megamenu_submenu] = Mega Menu Submenu

regions[homepage_slider] = Home Page Slider

; Stylesheets
stylesheets[all][] = css/layouts/cu-front/cu-front.layout.css

