#!/bin/bash
# updates all sites for a specific upstream
# will not update sites that have uninitialized environments (test or live)

MYSQL_CREDS=$(terminus connection:info legacy-creighton-hub.dev --fields='mysql_url' --format=string)
CURRENT_MYSQL_CREDS=$(terminus secrets:show legacy-creighton-hub.dev hub_db_url)
if [[ ${CURRENT_MYSQL_CREDS} != ${MYSQL_CREDS} ]] ; then
    terminus secrets:set legacy-creighton-admissions.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-adult-degrees.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-business.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-ccas.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-dentistry.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-ems.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-excellence.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-health-sciences.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-hub.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-law.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-med-school.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-nursing.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-spahp.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-student-life.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-www.dev hub_db_url $MYSQL_CREDS
    terminus secrets:set legacy-creighton-www15.dev hub_db_url $MYSQL_CREDS
fi