#!/bin/bash
# updates all sites for a specific upstream
# will not update sites that have uninitialized environments (test or live)

MYSQL_CREDS=$(terminus connection:info legacy-creighton-hub.dev --fields='mysql_url' --format=string)
terminus secrets:set legacy-creighton-med-school.uphubcred hub_db_url $MYSQL_CREDS