<?php

/**
 * Implements hook_form_alter().
 */
function ada_compliance_form_alter(&$form, &$form_state, $form_id)
{
  $form['#validate'][] = 'ada_compliance_form_validate';
  dpm($form['#validate']);
  //dpm($form);
  $form['field_file_image_alt_text']['und'][0]['#required'] = TRUE;
  $form['field_file_image_alt_text']['und'][0]['value']['#required'] = TRUE;
}
function ada_compliance_form_validate() {
  print("Hello");
}
/**
 * Implements hook_field_widget_form_alter().
 */
function ada_compliance_field_widget_form_alter(&$element, &$form_state, $context)
{
  //dpm($context);
  if ($context['field']['field_name'] == 'field_file_image_alt_text' && !empty($context['instance']['settings']['alt_field'])) {
    foreach (element_children($element) as $delta) {
      $element[$delta]['#process'][] = 'ada_compliance_image_field_widget_process';
    }
  }
}

/*
 * Function to help with processing each image field.
 */
function ada_compliance_image_field_widget_process($element, &$form_state, $form) {
  if ($element['alt']['#access']) {
    $element['alt']['#element_validate'] = array('_image_field_validate_alt_text');
  }
  return $element;
}

/*
 * Helper function to validate that alt text is provided for all image fields.
 */
function _image_field_validate_alt_text($element, &$form_state) {
  if (!in_array('file_managed_file_submit', $form_state['triggering_element']['#submit'])) {
    // If the image is not there, we do not check for empty values.
    $parents = $element['#parents'];
    $field = array_pop($parents);
    $image_field = drupal_array_get_nested_value($form_state['input'], $parents);
    // We check for the array key, so that it can be NULL (like if the user
    // submits the form without using the "upload" button).
    if (!array_key_exists($field, $image_field)) {
      return;
    }
    // Check if field is left emtpy.
    elseif (empty($image_field[$field])) {
      form_error($element, t('The field !title is required', array('!title' => $element['#title'])));
      return;
    }
  }
}