<?php

/**
 * Implements hook_form_alter().
 */
function ada_compliance_form_alter(&$form, &$form_state, $form_id)
{
  // alt attribute is considered to be an ADA compliance standard
  $form['field_file_image_alt_text']['und'][0]['#required'] = TRUE;
  $form['field_file_image_alt_text']['und'][0]['value']['#required'] = TRUE;

  if ('menu_edit_item' == $form_id) {
    $form['link_path']['#description'] .= ' ' . t('Enter %none to have a menu item that generates no link.', array('%none' => ''));
  }
}

/**
 * Implements hook_preprocess_block
 * @param $variables
 */
function ada_compliance_preprocess_block(&$variables) {
  if ($variables['block']->module == 'menu_block') {
    $variables['title_attributes_array']['id'][] = 'aria-label-block-menu-block-' . str_replace('_', '-', $variables['elements']['#config']['delta']);
    $variables['title_attributes_array']['class'][] = 'element-invisible';
  }
  if ($variables['block_html_id'] == 'block-menu-menu-transaction-menu') { //block-accessible-mega-menu-main-menu
    $arialabel = 'aria-label-' . $variables['block_html_id'];
    $variables['title_attributes_array']['id'] = $arialabel;
    $variables['title_attributes_array']['class'][] = 'element-invisible';
    $variables['content_attributes_array']['aria-labelledby'][] = $arialabel;
  }
}