<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 */

/**
* Implements hook_wysiwyg_editor_settings_alter().
*/
function creighton_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  if($context['profile']->editor == 'ckeditor') {
    $settings['forcePasteAsPlainText'] = TRUE;
    $settings['disableNativeSpellChecker'] = FALSE;
    // Prevents encoding of html entities, such as ampersands and quotes.
    // Needed on WWW site to prevent corruption of media tag.
    // @see http://drupal.org/node/803562
    $settings['entities'] = FALSE;
    $settings['basicEntities'] = FALSE;
    $settings['disableReadonlyStyling'] = TRUE;
    // Disable 'Advanced Content Filter (ACF), which was introduced
    // in CKEditor 4.1. ACF is unnecesary given WYSIWYG Filter module
    // is already in use.
    // @see http://drupal.org/node/1956778
    $settings['allowedContent'] = TRUE;
    $settings['extraPlugins'] = 'showblocks,video_filter,media,picture_ckeditor,drupal_path';
  }
}
