name = 2016 Creighton University Default
description = 2016 Creighton University's default site layout for 2016.
preview = preview.png
template = cu-default-2016-layout

; NOTE: Please make layouts/cu-default/cu-default.layout.inc regions match these regions else problems will ensue
regions[alert_header] = Alert Header
regions[header] = Main Header
regions[secondary_header] = Secondary Header
regions[header_image] = Header Image
regions[highlighted] = Highlighted
regions[help] = Help
regions[academics_program_title] = Academics Program Title
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer] = Footer

; Regions for Main Navigation

regions[main_nav] = Main Mega Navigation
regions[dropdown_menu] = Drop down toggle for menu

regions[header_searchbox] = Header Search
regions[header_tranlinks] = Transaction Links
regions[megamenu_dropdown] = Menu Dropdown
regions[megamenu_submenu] = Mega Menu Submenu

; Stylesheets
stylesheets[all][] = css/layouts/cu-default/cu-default.layout.css

