name = 2015 Front Page Layout
description = Creighton 2015 University's front page (homepage) layout.
preview = preview.png
template = cu-front-2015-layout

; NOTE: Please make layouts/cu-default/cu-default.layout.inc regions match these regions else problems will ensue
regions[alert_header] = Alert Header
regions[header] = Main Header
regions[secondary_header] = Secondary Header
regions[header_image] = Header Image
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/cu-front/cu-front.layout.css

