name: Pantheon web_d7stamp update hub Credentials
# run every 30 minutes
on:
  schedule:
    - cron: '*/30 * * * *'
# on:
#   push:
#     branches:
#       - uphubcred
env:
  # necessary variables/token for connecting to pantheon/github and setting up
  # the container for testing and deploy
  TERMINUS_TOKEN: ${{ secrets.BOT_TERMINUS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_wedsites_hub_creds:
    runs-on: ubuntu-latest

    steps:
    # use depth 0 to avoid shallow updates
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BOT_WORKFLOW_SSH }} 
        known_hosts: unnecessary
        config: |
          Host *
            StrictHostKeyChecking no

    - name: download terminus
      run: curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar

    - name: install terminus
      run: |
        sudo php installer.phar install
        mkdir -p ~/.terminus/plugins
        composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1

    - name: auth with pantheon, and update creds
      env:
        TERMINUS_TOKEN: ${{ secrets.BOT_TERMINUS_TOKEN }}
      run: terminus -n auth:login --machine-token="${{ env.TERMINUS_TOKEN }}"

    - name: update hub creds
      run: ./.ci/update/hub_credentials live
