<?php
/**
 * @file
 * front_page_social_media_cards.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function front_page_social_media_cards_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_fp_smc_body'.
  $field_bases['field_fp_smc_body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_body',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_fp_smc_color'.
  $field_bases['field_fp_smc_color'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_color',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '0054A6' => 'Primary Blue (#0054A6)',
        '002E6D' => 'Primary Blue Dark (#002E6D)',
        '95D2F3' => 'Primary Blue Light (#95D2F3)',
        '5D6468' => 'Primary Gray (#5D6468)',
        '019CDB' => 'Secondary Blue (#019CDB)',
        'FFA300' => 'Secondary Orange (#FFA300)',
        'FFCC4F' => 'Secondary Yellow (#FFCC4F)',
        '73B865' => 'Secondary Green (#73B865)',
        'F3EAC2' => 'Neutral Beige (#F3EAC2)',
        907257 => 'Neutral Brown (#907257)',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_fp_smc_image'.
  $field_bases['field_fp_smc_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_image',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  // Exported field_base: 'field_fp_smc_link'.
  $field_bases['field_fp_smc_link'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_link',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'link',
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'rel' => '',
        'target' => 'default',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'title' => 'optional',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
    ),
    'translatable' => 0,
    'type' => 'link_field',
  );

  // Exported field_base: 'field_fp_smc_order'.
  $field_bases['field_fp_smc_order'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_order',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  // Exported field_base: 'field_fp_smc_social_media'.
  $field_bases['field_fp_smc_social_media'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fp_smc_social_media',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'facebook' => 'Facebook',
        'instagram' => 'Instagram',
        'twitter' => 'Twitter',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
